version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install
          node-version: 14.17.3
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install Dependencies
          command: |
            npm run backend:install
      - run:
          name: Back-End Build & Deploy
          command: |
            npm run backend:deploy
      - run:
          name: Front-End Build & Front-End Deploy
          command: |
            npm run frontend:deploy
workflows:
    build_deploy:
        jobs:
        - deploy:
            filters:
                branches:
                  only: main
